name: "Merge Contentstack branches"

on:
  workflow_dispatch:
    inputs:
      api_key:
        type: string
        description: 'STACK_API_KEY. Default is development stack'
        default: "blta88cf8aaa9f0bdb2"
        required: true
      authorization:
        type: string
        description: 'STACK_MANAGEMENT_TOKEN. Default is development stack'
        default: "cs1327b2e47cf746839491e2c1"
        required: true
      base_branch:
        type: choice
        description: 'Base branch'
        default: "preview"
        required: true
        options:
          - "main"
          - "staging"
          - "preview"
      compare_branch:
        type: choice
        description: 'Compare branch'
        default: "staging"
        required: true
        options:
          - "main"
          - "staging"
          - "preview"
jobs:
  update_stack:
    name: "Merge branches in Contentstack. Only for the content type and global field modules of your stack"
    runs-on: ubuntu-latest
    env: 
      base_url: "https://eu-api.contentstack.com"
      default_merge_strategy: "overwrite_with_compare"
      merge_comment: "merge comment"
    steps:
      - name: Merging Branches API
        run: |
          echo "api_key: ${{ inputs.api_key }}"
          echo "authorization: ${{ inputs.authorization }}"
          echo "base_branch: ${{ inputs.base_branch }}"
          echo "compare_branch: ${{ inputs.compare_branch }}"
          echo '${{ env.base_url }}/v3/stacks/branches_merge?base_branch=${{ inputs.base_branch }}&compare_branch=${{ inputs.compare_branch }}&default_merge_strategy=${{ env.default_merge_strategy }}&merge_comment=${{ env.merge_comment }}'

          curl --location '${{ env.base_url }}/v3/stacks/branches_merge?base_branch=${{ inputs.base_branch }}&compare_branch=${{ inputs.compare_branch }}&default_merge_strategy=${{ env.default_merge_strategy }}&merge_comment=${{ env.merge_comment }}' \
          --header 'api_key: ${{ inputs.api_key }}' \
          --header 'authorization: ${{ inputs.authorization }}' \
          --header 'Content-Type: application/json' \
          --data '{ }'
